// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: executions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const claimExecution = `-- name: ClaimExecution :one
UPDATE executions
SET status = 'CLAIMED',
    locked_by = $2,
    lock_expires_at = NOW() + INTERVAL '1 second' * $3,
    attempt_count = attempt_count + 1,
    version = version + 1
WHERE execution_id = $1
  AND version = $4
  AND (status IN ('CREATED', 'FAILED'))
  AND (locked_by IS NULL OR lock_expires_at < NOW())
RETURNING execution_id, tenant_id, idempotency_key, status, attempt_count, max_attempts, locked_by, lock_expires_at, last_heartbeat_at, error_code, error_message, payload, payload_hash, created_at, updated_at, version
`

type ClaimExecutionParams struct {
	ExecutionID uuid.UUID
	LockedBy    pgtype.Text
	Column3     interface{}
	Version     int32
}

func (q *Queries) ClaimExecution(ctx context.Context, arg ClaimExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, claimExecution,
		arg.ExecutionID,
		arg.LockedBy,
		arg.Column3,
		arg.Version,
	)
	var i Execution
	err := row.Scan(
		&i.ExecutionID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.LastHeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const completeExecution = `-- name: CompleteExecution :one
UPDATE executions
SET status = 'SUCCEEDED',
    locked_by = NULL,
    lock_expires_at = NULL,
    version = version + 1
WHERE execution_id = $1
  AND version = $2
RETURNING execution_id, tenant_id, idempotency_key, status, attempt_count, max_attempts, locked_by, lock_expires_at, last_heartbeat_at, error_code, error_message, payload, payload_hash, created_at, updated_at, version
`

type CompleteExecutionParams struct {
	ExecutionID uuid.UUID
	Version     int32
}

func (q *Queries) CompleteExecution(ctx context.Context, arg CompleteExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, completeExecution, arg.ExecutionID, arg.Version)
	var i Execution
	err := row.Scan(
		&i.ExecutionID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.LastHeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const countExecutions = `-- name: CountExecutions :one
SELECT COUNT(*) FROM executions
WHERE tenant_id = $1
  AND ($2::execution_status IS NULL OR status = $2::execution_status)
`

type CountExecutionsParams struct {
	TenantID uuid.UUID
	Status   NullExecutionStatus
}

func (q *Queries) CountExecutions(ctx context.Context, arg CountExecutionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countExecutions, arg.TenantID, arg.Status)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createExecution = `-- name: CreateExecution :one
INSERT INTO executions (
    tenant_id, idempotency_key, status, attempt_count, max_attempts,
    payload, payload_hash, version
) VALUES (
    $1, $2, 'CREATED', 0, $3, $4, $5, 1
)
ON CONFLICT (tenant_id, idempotency_key) DO NOTHING
RETURNING execution_id, tenant_id, idempotency_key, status, attempt_count, max_attempts, locked_by, lock_expires_at, last_heartbeat_at, error_code, error_message, payload, payload_hash, created_at, updated_at, version
`

type CreateExecutionParams struct {
	TenantID       uuid.UUID
	IdempotencyKey string
	MaxAttempts    int32
	Payload        []byte
	PayloadHash    string
}

func (q *Queries) CreateExecution(ctx context.Context, arg CreateExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, createExecution,
		arg.TenantID,
		arg.IdempotencyKey,
		arg.MaxAttempts,
		arg.Payload,
		arg.PayloadHash,
	)
	var i Execution
	err := row.Scan(
		&i.ExecutionID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.LastHeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const failExecution = `-- name: FailExecution :one
UPDATE executions
SET status = 'FAILED',
    locked_by = NULL,
    lock_expires_at = NULL,
    error_code = $2,
    error_message = $3,
    version = version + 1
WHERE execution_id = $1
  AND version = $4
RETURNING execution_id, tenant_id, idempotency_key, status, attempt_count, max_attempts, locked_by, lock_expires_at, last_heartbeat_at, error_code, error_message, payload, payload_hash, created_at, updated_at, version
`

type FailExecutionParams struct {
	ExecutionID  uuid.UUID
	ErrorCode    pgtype.Text
	ErrorMessage pgtype.Text
	Version      int32
}

func (q *Queries) FailExecution(ctx context.Context, arg FailExecutionParams) (Execution, error) {
	row := q.db.QueryRow(ctx, failExecution,
		arg.ExecutionID,
		arg.ErrorCode,
		arg.ErrorMessage,
		arg.Version,
	)
	var i Execution
	err := row.Scan(
		&i.ExecutionID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.LastHeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const findClaimableExecutions = `-- name: FindClaimableExecutions :many
SELECT execution_id, tenant_id, idempotency_key, status, attempt_count, max_attempts, locked_by, lock_expires_at, last_heartbeat_at, error_code, error_message, payload, payload_hash, created_at, updated_at, version FROM executions
WHERE status IN ('CREATED', 'FAILED')
  AND (locked_by IS NULL OR lock_expires_at < NOW())
  AND attempt_count < max_attempts
ORDER BY created_at ASC
LIMIT $1
`

func (q *Queries) FindClaimableExecutions(ctx context.Context, limit int32) ([]Execution, error) {
	rows, err := q.db.Query(ctx, findClaimableExecutions, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Execution{}
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ExecutionID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.LockedBy,
			&i.LockExpiresAt,
			&i.LastHeartbeatAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Payload,
			&i.PayloadHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExecutionByID = `-- name: GetExecutionByID :one
SELECT execution_id, tenant_id, idempotency_key, status, attempt_count, max_attempts, locked_by, lock_expires_at, last_heartbeat_at, error_code, error_message, payload, payload_hash, created_at, updated_at, version FROM executions
WHERE execution_id = $1 AND tenant_id = $2
`

type GetExecutionByIDParams struct {
	ExecutionID uuid.UUID
	TenantID    uuid.UUID
}

func (q *Queries) GetExecutionByID(ctx context.Context, arg GetExecutionByIDParams) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecutionByID, arg.ExecutionID, arg.TenantID)
	var i Execution
	err := row.Scan(
		&i.ExecutionID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.LastHeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getExecutionByTenantAndIdempotencyKey = `-- name: GetExecutionByTenantAndIdempotencyKey :one
SELECT execution_id, tenant_id, idempotency_key, status, attempt_count, max_attempts, locked_by, lock_expires_at, last_heartbeat_at, error_code, error_message, payload, payload_hash, created_at, updated_at, version FROM executions
WHERE tenant_id = $1 AND idempotency_key = $2
`

type GetExecutionByTenantAndIdempotencyKeyParams struct {
	TenantID       uuid.UUID
	IdempotencyKey string
}

func (q *Queries) GetExecutionByTenantAndIdempotencyKey(ctx context.Context, arg GetExecutionByTenantAndIdempotencyKeyParams) (Execution, error) {
	row := q.db.QueryRow(ctx, getExecutionByTenantAndIdempotencyKey, arg.TenantID, arg.IdempotencyKey)
	var i Execution
	err := row.Scan(
		&i.ExecutionID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.LastHeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listExecutions = `-- name: ListExecutions :many
SELECT execution_id, tenant_id, idempotency_key, status, attempt_count, max_attempts, locked_by, lock_expires_at, last_heartbeat_at, error_code, error_message, payload, payload_hash, created_at, updated_at, version FROM executions
WHERE tenant_id = $1
  AND ($4::execution_status IS NULL OR status = $4::execution_status)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListExecutionsParams struct {
	TenantID uuid.UUID
	Limit    int32
	Offset   int32
	Status   NullExecutionStatus
}

func (q *Queries) ListExecutions(ctx context.Context, arg ListExecutionsParams) ([]Execution, error) {
	rows, err := q.db.Query(ctx, listExecutions,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.Status,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []Execution{}
	for rows.Next() {
		var i Execution
		if err := rows.Scan(
			&i.ExecutionID,
			&i.TenantID,
			&i.IdempotencyKey,
			&i.Status,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.LockedBy,
			&i.LockExpiresAt,
			&i.LastHeartbeatAt,
			&i.ErrorCode,
			&i.ErrorMessage,
			&i.Payload,
			&i.PayloadHash,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateExecutionStatus = `-- name: UpdateExecutionStatus :one
UPDATE executions
SET status = $2,
    version = version + 1
WHERE execution_id = $1
  AND version = $3
RETURNING execution_id, tenant_id, idempotency_key, status, attempt_count, max_attempts, locked_by, lock_expires_at, last_heartbeat_at, error_code, error_message, payload, payload_hash, created_at, updated_at, version
`

type UpdateExecutionStatusParams struct {
	ExecutionID uuid.UUID
	Status      ExecutionStatus
	Version     int32
}

func (q *Queries) UpdateExecutionStatus(ctx context.Context, arg UpdateExecutionStatusParams) (Execution, error) {
	row := q.db.QueryRow(ctx, updateExecutionStatus, arg.ExecutionID, arg.Status, arg.Version)
	var i Execution
	err := row.Scan(
		&i.ExecutionID,
		&i.TenantID,
		&i.IdempotencyKey,
		&i.Status,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.LockedBy,
		&i.LockExpiresAt,
		&i.LastHeartbeatAt,
		&i.ErrorCode,
		&i.ErrorMessage,
		&i.Payload,
		&i.PayloadHash,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
