// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package db

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

type ExecutionStatus string

const (
	ExecutionStatusCREATED   ExecutionStatus = "CREATED"
	ExecutionStatusCLAIMED   ExecutionStatus = "CLAIMED"
	ExecutionStatusRUNNING   ExecutionStatus = "RUNNING"
	ExecutionStatusSUCCEEDED ExecutionStatus = "SUCCEEDED"
	ExecutionStatusFAILED    ExecutionStatus = "FAILED"
	ExecutionStatusCANCELED  ExecutionStatus = "CANCELED"
	ExecutionStatusTIMEDOUT  ExecutionStatus = "TIMED_OUT"
)

func (e *ExecutionStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExecutionStatus(s)
	case string:
		*e = ExecutionStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ExecutionStatus: %T", src)
	}
	return nil
}

type NullExecutionStatus struct {
	ExecutionStatus ExecutionStatus
	Valid           bool // Valid is true if ExecutionStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExecutionStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ExecutionStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExecutionStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExecutionStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExecutionStatus), nil
}

type Execution struct {
	ExecutionID     uuid.UUID
	TenantID        uuid.UUID
	IdempotencyKey  string
	Status          ExecutionStatus
	AttemptCount    int32
	MaxAttempts     int32
	LockedBy        pgtype.Text
	LockExpiresAt   pgtype.Timestamptz
	LastHeartbeatAt pgtype.Timestamptz
	ErrorCode       pgtype.Text
	ErrorMessage    pgtype.Text
	Payload         []byte
	PayloadHash     string
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
	Version         int32
}
