// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: outbox.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const cleanupOldEvents = `-- name: CleanupOldEvents :exec
DELETE FROM outbox_events
WHERE sent = TRUE AND sent_at < $1
`

func (q *Queries) CleanupOldEvents(ctx context.Context, sentAt pgtype.Timestamptz) error {
	_, err := q.db.Exec(ctx, cleanupOldEvents, sentAt)
	return err
}

const countUnsentEvents = `-- name: CountUnsentEvents :one
SELECT COUNT(*) FROM outbox_events WHERE sent = FALSE
`

func (q *Queries) CountUnsentEvents(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnsentEvents)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const fetchUnsentEvents = `-- name: FetchUnsentEvents :many
SELECT event_id, aggregate_type, aggregate_id, event_type, payload, metadata, sequence_number, created_at, sent_at, sent FROM outbox_events
WHERE sent = FALSE
ORDER BY sequence_number ASC
LIMIT $1
FOR UPDATE SKIP LOCKED
`

func (q *Queries) FetchUnsentEvents(ctx context.Context, limit int32) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, fetchUnsentEvents, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.EventID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Metadata,
			&i.SequenceNumber,
			&i.CreatedAt,
			&i.SentAt,
			&i.Sent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertOutboxEvent = `-- name: InsertOutboxEvent :exec
INSERT INTO outbox_events (
    aggregate_type, aggregate_id, event_type, payload, metadata
) VALUES ($1, $2, $3, $4, $5)
`

type InsertOutboxEventParams struct {
	AggregateType string
	AggregateID   uuid.UUID
	EventType     string
	Payload       []byte
	Metadata      []byte
}

func (q *Queries) InsertOutboxEvent(ctx context.Context, arg InsertOutboxEventParams) error {
	_, err := q.db.Exec(ctx, insertOutboxEvent,
		arg.AggregateType,
		arg.AggregateID,
		arg.EventType,
		arg.Payload,
		arg.Metadata,
	)
	return err
}

const listOutboxEventsByAggregate = `-- name: ListOutboxEventsByAggregate :many
SELECT event_id, aggregate_type, aggregate_id, event_type, payload, metadata, sequence_number, created_at, sent_at, sent FROM outbox_events
WHERE aggregate_type = $1 AND aggregate_id = $2
ORDER BY sequence_number ASC
`

type ListOutboxEventsByAggregateParams struct {
	AggregateType string
	AggregateID   uuid.UUID
}

func (q *Queries) ListOutboxEventsByAggregate(ctx context.Context, arg ListOutboxEventsByAggregateParams) ([]OutboxEvent, error) {
	rows, err := q.db.Query(ctx, listOutboxEventsByAggregate, arg.AggregateType, arg.AggregateID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []OutboxEvent{}
	for rows.Next() {
		var i OutboxEvent
		if err := rows.Scan(
			&i.EventID,
			&i.AggregateType,
			&i.AggregateID,
			&i.EventType,
			&i.Payload,
			&i.Metadata,
			&i.SequenceNumber,
			&i.CreatedAt,
			&i.SentAt,
			&i.Sent,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markEventsSent = `-- name: MarkEventsSent :exec
UPDATE outbox_events
SET sent = TRUE, sent_at = NOW()
WHERE event_id = ANY($1::uuid[])
`

func (q *Queries) MarkEventsSent(ctx context.Context, dollar_1 []uuid.UUID) error {
	_, err := q.db.Exec(ctx, markEventsSent, dollar_1)
	return err
}
