# Set AWS_PROMETHEUS_ENDPOINT to terraform output amp_remote_write_url
apiVersion: apps/v1
kind: Deployment
metadata:
  name: adot-amp-collector
  namespace: monitoring
spec:
  template:
    spec:
      containers:
        - name: aws-otel-collector
          env:
            - name: AWS_REGION
              value: us-east-1
            - name: AWS_PROMETHEUS_ENDPOINT
              value: https://aps-workspaces.us-east-1.amazonaws.com/workspaces/YOUR_WORKSPACE_ID/api/v1/remote_write
