// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: audit_trail.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countAuditByExecution = `-- name: CountAuditByExecution :one
SELECT COUNT(*) FROM audit_trail
WHERE sop_execution_id = $1
`

func (q *Queries) CountAuditByExecution(ctx context.Context, sopExecutionID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countAuditByExecution, sopExecutionID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertAuditEntry = `-- name: InsertAuditEntry :one
INSERT INTO audit_trail (
    sop_execution_id, sop_id, tenant_id, step_id, agent_type,
    action, input_hash, output_hash, model_used, latency_ms,
    tokens_used, compliance_tags
) VALUES (
    $1, $2, $3, $4, $5,
    $6, $7, $8, $9, $10,
    $11, $12
)
RETURNING audit_id, sop_execution_id, sop_id, tenant_id, step_id, agent_type, action, input_hash, output_hash, model_used, latency_ms, tokens_used, compliance_tags, created_at
`

type InsertAuditEntryParams struct {
	SopExecutionID uuid.UUID
	SopID          string
	TenantID       uuid.UUID
	StepID         string
	AgentType      AgentStepType
	Action         string
	InputHash      string
	OutputHash     string
	ModelUsed      pgtype.Text
	LatencyMs      int64
	TokensUsed     pgtype.Int4
	ComplianceTags []string
}

func (q *Queries) InsertAuditEntry(ctx context.Context, arg InsertAuditEntryParams) (AuditTrail, error) {
	row := q.db.QueryRow(ctx, insertAuditEntry,
		arg.SopExecutionID,
		arg.SopID,
		arg.TenantID,
		arg.StepID,
		arg.AgentType,
		arg.Action,
		arg.InputHash,
		arg.OutputHash,
		arg.ModelUsed,
		arg.LatencyMs,
		arg.TokensUsed,
		arg.ComplianceTags,
	)
	var i AuditTrail
	err := row.Scan(
		&i.AuditID,
		&i.SopExecutionID,
		&i.SopID,
		&i.TenantID,
		&i.StepID,
		&i.AgentType,
		&i.Action,
		&i.InputHash,
		&i.OutputHash,
		&i.ModelUsed,
		&i.LatencyMs,
		&i.TokensUsed,
		&i.ComplianceTags,
		&i.CreatedAt,
	)
	return i, err
}

const listAuditByExecution = `-- name: ListAuditByExecution :many
SELECT audit_id, sop_execution_id, sop_id, tenant_id, step_id, agent_type, action, input_hash, output_hash, model_used, latency_ms, tokens_used, compliance_tags, created_at FROM audit_trail
WHERE sop_execution_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListAuditByExecution(ctx context.Context, sopExecutionID uuid.UUID) ([]AuditTrail, error) {
	rows, err := q.db.Query(ctx, listAuditByExecution, sopExecutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditTrail{}
	for rows.Next() {
		var i AuditTrail
		if err := rows.Scan(
			&i.AuditID,
			&i.SopExecutionID,
			&i.SopID,
			&i.TenantID,
			&i.StepID,
			&i.AgentType,
			&i.Action,
			&i.InputHash,
			&i.OutputHash,
			&i.ModelUsed,
			&i.LatencyMs,
			&i.TokensUsed,
			&i.ComplianceTags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAuditByTenantAndSOP = `-- name: ListAuditByTenantAndSOP :many
SELECT audit_id, sop_execution_id, sop_id, tenant_id, step_id, agent_type, action, input_hash, output_hash, model_used, latency_ms, tokens_used, compliance_tags, created_at FROM audit_trail
WHERE tenant_id = $1
  AND sop_id = $2
ORDER BY created_at DESC
LIMIT $3 OFFSET $4
`

type ListAuditByTenantAndSOPParams struct {
	TenantID uuid.UUID
	SopID    string
	Limit    int32
	Offset   int32
}

func (q *Queries) ListAuditByTenantAndSOP(ctx context.Context, arg ListAuditByTenantAndSOPParams) ([]AuditTrail, error) {
	rows, err := q.db.Query(ctx, listAuditByTenantAndSOP,
		arg.TenantID,
		arg.SopID,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []AuditTrail{}
	for rows.Next() {
		var i AuditTrail
		if err := rows.Scan(
			&i.AuditID,
			&i.SopExecutionID,
			&i.SopID,
			&i.TenantID,
			&i.StepID,
			&i.AgentType,
			&i.Action,
			&i.InputHash,
			&i.OutputHash,
			&i.ModelUsed,
			&i.LatencyMs,
			&i.TokensUsed,
			&i.ComplianceTags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
