// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: consumer_offsets.sql

package db

import (
	"context"
)

const getConsumerOffset = `-- name: GetConsumerOffset :one
SELECT consumer_group, last_processed_seq, updated_at FROM consumer_offsets WHERE consumer_group = $1
`

func (q *Queries) GetConsumerOffset(ctx context.Context, consumerGroup string) (ConsumerOffset, error) {
	row := q.db.QueryRow(ctx, getConsumerOffset, consumerGroup)
	var i ConsumerOffset
	err := row.Scan(&i.ConsumerGroup, &i.LastProcessedSeq, &i.UpdatedAt)
	return i, err
}

const upsertConsumerOffset = `-- name: UpsertConsumerOffset :exec
INSERT INTO consumer_offsets (consumer_group, last_processed_seq, updated_at)
VALUES ($1, $2, NOW())
ON CONFLICT (consumer_group) DO UPDATE
SET last_processed_seq = GREATEST(consumer_offsets.last_processed_seq, $2),
    updated_at = NOW()
`

type UpsertConsumerOffsetParams struct {
	ConsumerGroup    string
	LastProcessedSeq int64
}

func (q *Queries) UpsertConsumerOffset(ctx context.Context, arg UpsertConsumerOffsetParams) error {
	_, err := q.db.Exec(ctx, upsertConsumerOffset, arg.ConsumerGroup, arg.LastProcessedSeq)
	return err
}
