// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: dlq.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countDLQEvents = `-- name: CountDLQEvents :one
SELECT COUNT(*) FROM dead_letter_events WHERE consumer_group = $1
`

func (q *Queries) CountDLQEvents(ctx context.Context, consumerGroup string) (int64, error) {
	row := q.db.QueryRow(ctx, countDLQEvents, consumerGroup)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteDLQEvent = `-- name: DeleteDLQEvent :exec
DELETE FROM dead_letter_events WHERE id = $1
`

func (q *Queries) DeleteDLQEvent(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteDLQEvent, id)
	return err
}

const getDLQEventByEventID = `-- name: GetDLQEventByEventID :one
SELECT id, event_id, consumer_group, event_type, aggregate_type, aggregate_id, payload, metadata, error_message, attempt_count, max_attempts, created_at, last_failed_at FROM dead_letter_events WHERE event_id = $1 AND consumer_group = $2
`

type GetDLQEventByEventIDParams struct {
	EventID       uuid.UUID
	ConsumerGroup string
}

func (q *Queries) GetDLQEventByEventID(ctx context.Context, arg GetDLQEventByEventIDParams) (DeadLetterEvent, error) {
	row := q.db.QueryRow(ctx, getDLQEventByEventID, arg.EventID, arg.ConsumerGroup)
	var i DeadLetterEvent
	err := row.Scan(
		&i.ID,
		&i.EventID,
		&i.ConsumerGroup,
		&i.EventType,
		&i.AggregateType,
		&i.AggregateID,
		&i.Payload,
		&i.Metadata,
		&i.ErrorMessage,
		&i.AttemptCount,
		&i.MaxAttempts,
		&i.CreatedAt,
		&i.LastFailedAt,
	)
	return i, err
}

const insertDLQEvent = `-- name: InsertDLQEvent :exec
INSERT INTO dead_letter_events (
    event_id, consumer_group, event_type, aggregate_type, aggregate_id,
    payload, metadata, error_message, attempt_count, max_attempts
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
`

type InsertDLQEventParams struct {
	EventID       uuid.UUID
	ConsumerGroup string
	EventType     string
	AggregateType string
	AggregateID   uuid.UUID
	Payload       []byte
	Metadata      []byte
	ErrorMessage  string
	AttemptCount  int32
	MaxAttempts   int32
}

func (q *Queries) InsertDLQEvent(ctx context.Context, arg InsertDLQEventParams) error {
	_, err := q.db.Exec(ctx, insertDLQEvent,
		arg.EventID,
		arg.ConsumerGroup,
		arg.EventType,
		arg.AggregateType,
		arg.AggregateID,
		arg.Payload,
		arg.Metadata,
		arg.ErrorMessage,
		arg.AttemptCount,
		arg.MaxAttempts,
	)
	return err
}

const listDLQEvents = `-- name: ListDLQEvents :many
SELECT id, event_id, consumer_group, event_type, aggregate_type, aggregate_id, payload, metadata, error_message, attempt_count, max_attempts, created_at, last_failed_at FROM dead_letter_events
WHERE consumer_group = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListDLQEventsParams struct {
	ConsumerGroup string
	Limit         int32
	Offset        int32
}

func (q *Queries) ListDLQEvents(ctx context.Context, arg ListDLQEventsParams) ([]DeadLetterEvent, error) {
	rows, err := q.db.Query(ctx, listDLQEvents, arg.ConsumerGroup, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []DeadLetterEvent{}
	for rows.Next() {
		var i DeadLetterEvent
		if err := rows.Scan(
			&i.ID,
			&i.EventID,
			&i.ConsumerGroup,
			&i.EventType,
			&i.AggregateType,
			&i.AggregateID,
			&i.Payload,
			&i.Metadata,
			&i.ErrorMessage,
			&i.AttemptCount,
			&i.MaxAttempts,
			&i.CreatedAt,
			&i.LastFailedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
