// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: hitl_requests.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingHITLRequests = `-- name: CountPendingHITLRequests :one
SELECT COUNT(*) FROM hitl_requests
WHERE tenant_id = $1
  AND decision = 'PENDING'
`

func (q *Queries) CountPendingHITLRequests(ctx context.Context, tenantID uuid.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingHITLRequests, tenantID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createHITLRequest = `-- name: CreateHITLRequest :one
INSERT INTO hitl_requests (
    sop_execution_id, sop_id, tenant_id, step_id, step_name,
    decision, deadline, payload, temporal_workflow_id, temporal_run_id, version
) VALUES (
    $1, $2, $3, $4, $5,
    'PENDING', $6, $7, $8, $9, 1
)
RETURNING request_id, sop_execution_id, sop_id, tenant_id, step_id, step_name, decision, decided_by, decision_reason, decided_at, deadline, payload, temporal_workflow_id, temporal_run_id, created_at, updated_at, version
`

type CreateHITLRequestParams struct {
	SopExecutionID     uuid.UUID
	SopID              string
	TenantID           uuid.UUID
	StepID             string
	StepName           string
	Deadline           pgtype.Timestamptz
	Payload            []byte
	TemporalWorkflowID string
	TemporalRunID      string
}

func (q *Queries) CreateHITLRequest(ctx context.Context, arg CreateHITLRequestParams) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, createHITLRequest,
		arg.SopExecutionID,
		arg.SopID,
		arg.TenantID,
		arg.StepID,
		arg.StepName,
		arg.Deadline,
		arg.Payload,
		arg.TemporalWorkflowID,
		arg.TemporalRunID,
	)
	var i HitlRequest
	err := row.Scan(
		&i.RequestID,
		&i.SopExecutionID,
		&i.SopID,
		&i.TenantID,
		&i.StepID,
		&i.StepName,
		&i.Decision,
		&i.DecidedBy,
		&i.DecisionReason,
		&i.DecidedAt,
		&i.Deadline,
		&i.Payload,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getHITLRequestByID = `-- name: GetHITLRequestByID :one
SELECT request_id, sop_execution_id, sop_id, tenant_id, step_id, step_name, decision, decided_by, decision_reason, decided_at, deadline, payload, temporal_workflow_id, temporal_run_id, created_at, updated_at, version FROM hitl_requests
WHERE request_id = $1 AND tenant_id = $2
`

type GetHITLRequestByIDParams struct {
	RequestID uuid.UUID
	TenantID  uuid.UUID
}

func (q *Queries) GetHITLRequestByID(ctx context.Context, arg GetHITLRequestByIDParams) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, getHITLRequestByID, arg.RequestID, arg.TenantID)
	var i HitlRequest
	err := row.Scan(
		&i.RequestID,
		&i.SopExecutionID,
		&i.SopID,
		&i.TenantID,
		&i.StepID,
		&i.StepName,
		&i.Decision,
		&i.DecidedBy,
		&i.DecisionReason,
		&i.DecidedAt,
		&i.Deadline,
		&i.Payload,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listHITLRequestsByExecution = `-- name: ListHITLRequestsByExecution :many
SELECT request_id, sop_execution_id, sop_id, tenant_id, step_id, step_name, decision, decided_by, decision_reason, decided_at, deadline, payload, temporal_workflow_id, temporal_run_id, created_at, updated_at, version FROM hitl_requests
WHERE sop_execution_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListHITLRequestsByExecution(ctx context.Context, sopExecutionID uuid.UUID) ([]HitlRequest, error) {
	rows, err := q.db.Query(ctx, listHITLRequestsByExecution, sopExecutionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HitlRequest{}
	for rows.Next() {
		var i HitlRequest
		if err := rows.Scan(
			&i.RequestID,
			&i.SopExecutionID,
			&i.SopID,
			&i.TenantID,
			&i.StepID,
			&i.StepName,
			&i.Decision,
			&i.DecidedBy,
			&i.DecisionReason,
			&i.DecidedAt,
			&i.Deadline,
			&i.Payload,
			&i.TemporalWorkflowID,
			&i.TemporalRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listOverdueHITLRequests = `-- name: ListOverdueHITLRequests :many
SELECT request_id, sop_execution_id, sop_id, tenant_id, step_id, step_name, decision, decided_by, decision_reason, decided_at, deadline, payload, temporal_workflow_id, temporal_run_id, created_at, updated_at, version FROM hitl_requests
WHERE decision = 'PENDING'
  AND deadline < NOW()
ORDER BY deadline ASC
LIMIT $1
`

func (q *Queries) ListOverdueHITLRequests(ctx context.Context, limit int32) ([]HitlRequest, error) {
	rows, err := q.db.Query(ctx, listOverdueHITLRequests, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HitlRequest{}
	for rows.Next() {
		var i HitlRequest
		if err := rows.Scan(
			&i.RequestID,
			&i.SopExecutionID,
			&i.SopID,
			&i.TenantID,
			&i.StepID,
			&i.StepName,
			&i.Decision,
			&i.DecidedBy,
			&i.DecisionReason,
			&i.DecidedAt,
			&i.Deadline,
			&i.Payload,
			&i.TemporalWorkflowID,
			&i.TemporalRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingHITLRequests = `-- name: ListPendingHITLRequests :many
SELECT request_id, sop_execution_id, sop_id, tenant_id, step_id, step_name, decision, decided_by, decision_reason, decided_at, deadline, payload, temporal_workflow_id, temporal_run_id, created_at, updated_at, version FROM hitl_requests
WHERE tenant_id = $1
  AND decision = 'PENDING'
ORDER BY deadline ASC
LIMIT $2 OFFSET $3
`

type ListPendingHITLRequestsParams struct {
	TenantID uuid.UUID
	Limit    int32
	Offset   int32
}

func (q *Queries) ListPendingHITLRequests(ctx context.Context, arg ListPendingHITLRequestsParams) ([]HitlRequest, error) {
	rows, err := q.db.Query(ctx, listPendingHITLRequests, arg.TenantID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []HitlRequest{}
	for rows.Next() {
		var i HitlRequest
		if err := rows.Scan(
			&i.RequestID,
			&i.SopExecutionID,
			&i.SopID,
			&i.TenantID,
			&i.StepID,
			&i.StepName,
			&i.Decision,
			&i.DecidedBy,
			&i.DecisionReason,
			&i.DecidedAt,
			&i.Deadline,
			&i.Payload,
			&i.TemporalWorkflowID,
			&i.TemporalRunID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateHITLDecision = `-- name: UpdateHITLDecision :one
UPDATE hitl_requests
SET decision = $2,
    decided_by = $3,
    decision_reason = $4,
    decided_at = NOW(),
    version = version + 1
WHERE request_id = $1
  AND decision = 'PENDING'
  AND version = $5
RETURNING request_id, sop_execution_id, sop_id, tenant_id, step_id, step_name, decision, decided_by, decision_reason, decided_at, deadline, payload, temporal_workflow_id, temporal_run_id, created_at, updated_at, version
`

type UpdateHITLDecisionParams struct {
	RequestID      uuid.UUID
	Decision       HitlDecision
	DecidedBy      pgtype.Text
	DecisionReason pgtype.Text
	Version        int32
}

func (q *Queries) UpdateHITLDecision(ctx context.Context, arg UpdateHITLDecisionParams) (HitlRequest, error) {
	row := q.db.QueryRow(ctx, updateHITLDecision,
		arg.RequestID,
		arg.Decision,
		arg.DecidedBy,
		arg.DecisionReason,
		arg.Version,
	)
	var i HitlRequest
	err := row.Scan(
		&i.RequestID,
		&i.SopExecutionID,
		&i.SopID,
		&i.TenantID,
		&i.StepID,
		&i.StepName,
		&i.Decision,
		&i.DecidedBy,
		&i.DecisionReason,
		&i.DecidedAt,
		&i.Deadline,
		&i.Payload,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
