// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: processing.sql

package db

import (
	"context"

	"github.com/google/uuid"
)

const countCompletedByExecution = `-- name: CountCompletedByExecution :many
SELECT execution_id, COUNT(*) as completion_count
FROM processing_log
WHERE action = 'COMPLETED'
GROUP BY execution_id
HAVING COUNT(*) > 1
`

type CountCompletedByExecutionRow struct {
	ExecutionID     uuid.UUID
	CompletionCount int64
}

func (q *Queries) CountCompletedByExecution(ctx context.Context) ([]CountCompletedByExecutionRow, error) {
	rows, err := q.db.Query(ctx, countCompletedByExecution)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []CountCompletedByExecutionRow{}
	for rows.Next() {
		var i CountCompletedByExecutionRow
		if err := rows.Scan(&i.ExecutionID, &i.CompletionCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertProcessedEvent = `-- name: InsertProcessedEvent :one
INSERT INTO processed_events (event_id, consumer_group)
VALUES ($1, $2)
ON CONFLICT (event_id, consumer_group) DO NOTHING
RETURNING event_id
`

type InsertProcessedEventParams struct {
	EventID       uuid.UUID
	ConsumerGroup string
}

func (q *Queries) InsertProcessedEvent(ctx context.Context, arg InsertProcessedEventParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, insertProcessedEvent, arg.EventID, arg.ConsumerGroup)
	var event_id uuid.UUID
	err := row.Scan(&event_id)
	return event_id, err
}

const insertProcessingLog = `-- name: InsertProcessingLog :exec
INSERT INTO processing_log (execution_id, worker_id, action, attempt_number)
VALUES ($1, $2, $3, $4)
`

type InsertProcessingLogParams struct {
	ExecutionID   uuid.UUID
	WorkerID      string
	Action        string
	AttemptNumber int32
}

func (q *Queries) InsertProcessingLog(ctx context.Context, arg InsertProcessingLogParams) error {
	_, err := q.db.Exec(ctx, insertProcessingLog,
		arg.ExecutionID,
		arg.WorkerID,
		arg.Action,
		arg.AttemptNumber,
	)
	return err
}

const listProcessingLogByExecution = `-- name: ListProcessingLogByExecution :many
SELECT log_id, execution_id, worker_id, action, attempt_number, created_at FROM processing_log
WHERE execution_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListProcessingLogByExecution(ctx context.Context, executionID uuid.UUID) ([]ProcessingLog, error) {
	rows, err := q.db.Query(ctx, listProcessingLogByExecution, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ProcessingLog{}
	for rows.Next() {
		var i ProcessingLog
		if err := rows.Scan(
			&i.LogID,
			&i.ExecutionID,
			&i.WorkerID,
			&i.Action,
			&i.AttemptNumber,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
