// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: sop_executions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const completeSOPExecution = `-- name: CompleteSOPExecution :one
UPDATE sop_executions
SET status = 'COMPLETED',
    output_payload = $2,
    completed_at = NOW(),
    version = version + 1
WHERE sop_execution_id = $1
  AND version = $3
RETURNING sop_execution_id, sop_id, tenant_id, industry, current_step, status, input_payload, output_payload, temporal_workflow_id, temporal_run_id, started_at, completed_at, created_at, updated_at, version
`

type CompleteSOPExecutionParams struct {
	SopExecutionID uuid.UUID
	OutputPayload  []byte
	Version        int32
}

func (q *Queries) CompleteSOPExecution(ctx context.Context, arg CompleteSOPExecutionParams) (SopExecution, error) {
	row := q.db.QueryRow(ctx, completeSOPExecution, arg.SopExecutionID, arg.OutputPayload, arg.Version)
	var i SopExecution
	err := row.Scan(
		&i.SopExecutionID,
		&i.SopID,
		&i.TenantID,
		&i.Industry,
		&i.CurrentStep,
		&i.Status,
		&i.InputPayload,
		&i.OutputPayload,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const countSOPExecutions = `-- name: CountSOPExecutions :one
SELECT COUNT(*) FROM sop_executions
WHERE tenant_id = $1
  AND ($2::VARCHAR IS NULL OR sop_id = $2::VARCHAR)
  AND ($3::sop_execution_status IS NULL OR status = $3::sop_execution_status)
  AND ($4::sop_industry IS NULL OR industry = $4::sop_industry)
`

type CountSOPExecutionsParams struct {
	TenantID uuid.UUID
	SopID    pgtype.Text
	Status   NullSopExecutionStatus
	Industry NullSopIndustry
}

func (q *Queries) CountSOPExecutions(ctx context.Context, arg CountSOPExecutionsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countSOPExecutions,
		arg.TenantID,
		arg.SopID,
		arg.Status,
		arg.Industry,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createSOPExecution = `-- name: CreateSOPExecution :one
INSERT INTO sop_executions (
    sop_id, tenant_id, industry, current_step, status,
    input_payload, temporal_workflow_id, temporal_run_id, version
) VALUES (
    $1, $2, $3, 'intake', 'PENDING', $4, $5, $6, 1
)
RETURNING sop_execution_id, sop_id, tenant_id, industry, current_step, status, input_payload, output_payload, temporal_workflow_id, temporal_run_id, started_at, completed_at, created_at, updated_at, version
`

type CreateSOPExecutionParams struct {
	SopID              string
	TenantID           uuid.UUID
	Industry           SopIndustry
	InputPayload       []byte
	TemporalWorkflowID pgtype.Text
	TemporalRunID      pgtype.Text
}

func (q *Queries) CreateSOPExecution(ctx context.Context, arg CreateSOPExecutionParams) (SopExecution, error) {
	row := q.db.QueryRow(ctx, createSOPExecution,
		arg.SopID,
		arg.TenantID,
		arg.Industry,
		arg.InputPayload,
		arg.TemporalWorkflowID,
		arg.TemporalRunID,
	)
	var i SopExecution
	err := row.Scan(
		&i.SopExecutionID,
		&i.SopID,
		&i.TenantID,
		&i.Industry,
		&i.CurrentStep,
		&i.Status,
		&i.InputPayload,
		&i.OutputPayload,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const failSOPExecution = `-- name: FailSOPExecution :one
UPDATE sop_executions
SET status = 'FAILED',
    completed_at = NOW(),
    version = version + 1
WHERE sop_execution_id = $1
  AND version = $2
RETURNING sop_execution_id, sop_id, tenant_id, industry, current_step, status, input_payload, output_payload, temporal_workflow_id, temporal_run_id, started_at, completed_at, created_at, updated_at, version
`

type FailSOPExecutionParams struct {
	SopExecutionID uuid.UUID
	Version        int32
}

func (q *Queries) FailSOPExecution(ctx context.Context, arg FailSOPExecutionParams) (SopExecution, error) {
	row := q.db.QueryRow(ctx, failSOPExecution, arg.SopExecutionID, arg.Version)
	var i SopExecution
	err := row.Scan(
		&i.SopExecutionID,
		&i.SopID,
		&i.TenantID,
		&i.Industry,
		&i.CurrentStep,
		&i.Status,
		&i.InputPayload,
		&i.OutputPayload,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getSOPExecutionByID = `-- name: GetSOPExecutionByID :one
SELECT sop_execution_id, sop_id, tenant_id, industry, current_step, status, input_payload, output_payload, temporal_workflow_id, temporal_run_id, started_at, completed_at, created_at, updated_at, version FROM sop_executions
WHERE sop_execution_id = $1 AND tenant_id = $2
`

type GetSOPExecutionByIDParams struct {
	SopExecutionID uuid.UUID
	TenantID       uuid.UUID
}

func (q *Queries) GetSOPExecutionByID(ctx context.Context, arg GetSOPExecutionByIDParams) (SopExecution, error) {
	row := q.db.QueryRow(ctx, getSOPExecutionByID, arg.SopExecutionID, arg.TenantID)
	var i SopExecution
	err := row.Scan(
		&i.SopExecutionID,
		&i.SopID,
		&i.TenantID,
		&i.Industry,
		&i.CurrentStep,
		&i.Status,
		&i.InputPayload,
		&i.OutputPayload,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const getSOPExecutionByWorkflowID = `-- name: GetSOPExecutionByWorkflowID :one
SELECT sop_execution_id, sop_id, tenant_id, industry, current_step, status, input_payload, output_payload, temporal_workflow_id, temporal_run_id, started_at, completed_at, created_at, updated_at, version FROM sop_executions
WHERE temporal_workflow_id = $1
`

func (q *Queries) GetSOPExecutionByWorkflowID(ctx context.Context, temporalWorkflowID pgtype.Text) (SopExecution, error) {
	row := q.db.QueryRow(ctx, getSOPExecutionByWorkflowID, temporalWorkflowID)
	var i SopExecution
	err := row.Scan(
		&i.SopExecutionID,
		&i.SopID,
		&i.TenantID,
		&i.Industry,
		&i.CurrentStep,
		&i.Status,
		&i.InputPayload,
		&i.OutputPayload,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}

const listSOPExecutions = `-- name: ListSOPExecutions :many
SELECT sop_execution_id, sop_id, tenant_id, industry, current_step, status, input_payload, output_payload, temporal_workflow_id, temporal_run_id, started_at, completed_at, created_at, updated_at, version FROM sop_executions
WHERE tenant_id = $1
  AND ($4::VARCHAR IS NULL OR sop_id = $4::VARCHAR)
  AND ($5::sop_execution_status IS NULL OR status = $5::sop_execution_status)
  AND ($6::sop_industry IS NULL OR industry = $6::sop_industry)
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type ListSOPExecutionsParams struct {
	TenantID uuid.UUID
	Limit    int32
	Offset   int32
	SopID    pgtype.Text
	Status   NullSopExecutionStatus
	Industry NullSopIndustry
}

func (q *Queries) ListSOPExecutions(ctx context.Context, arg ListSOPExecutionsParams) ([]SopExecution, error) {
	rows, err := q.db.Query(ctx, listSOPExecutions,
		arg.TenantID,
		arg.Limit,
		arg.Offset,
		arg.SopID,
		arg.Status,
		arg.Industry,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []SopExecution{}
	for rows.Next() {
		var i SopExecution
		if err := rows.Scan(
			&i.SopExecutionID,
			&i.SopID,
			&i.TenantID,
			&i.Industry,
			&i.CurrentStep,
			&i.Status,
			&i.InputPayload,
			&i.OutputPayload,
			&i.TemporalWorkflowID,
			&i.TemporalRunID,
			&i.StartedAt,
			&i.CompletedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.Version,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateSOPExecutionStatus = `-- name: UpdateSOPExecutionStatus :one
UPDATE sop_executions
SET status = $2,
    current_step = $3,
    version = version + 1
WHERE sop_execution_id = $1
  AND version = $4
RETURNING sop_execution_id, sop_id, tenant_id, industry, current_step, status, input_payload, output_payload, temporal_workflow_id, temporal_run_id, started_at, completed_at, created_at, updated_at, version
`

type UpdateSOPExecutionStatusParams struct {
	SopExecutionID uuid.UUID
	Status         SopExecutionStatus
	CurrentStep    string
	Version        int32
}

func (q *Queries) UpdateSOPExecutionStatus(ctx context.Context, arg UpdateSOPExecutionStatusParams) (SopExecution, error) {
	row := q.db.QueryRow(ctx, updateSOPExecutionStatus,
		arg.SopExecutionID,
		arg.Status,
		arg.CurrentStep,
		arg.Version,
	)
	var i SopExecution
	err := row.Scan(
		&i.SopExecutionID,
		&i.SopID,
		&i.TenantID,
		&i.Industry,
		&i.CurrentStep,
		&i.Status,
		&i.InputPayload,
		&i.OutputPayload,
		&i.TemporalWorkflowID,
		&i.TemporalRunID,
		&i.StartedAt,
		&i.CompletedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Version,
	)
	return i, err
}
