// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: transitions.sql

package db

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const insertTransition = `-- name: InsertTransition :exec
INSERT INTO execution_transitions (
    execution_id, from_status, to_status, triggered_by, reason, metadata
) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTransitionParams struct {
	ExecutionID uuid.UUID
	FromStatus  ExecutionStatus
	ToStatus    ExecutionStatus
	TriggeredBy string
	Reason      pgtype.Text
	Metadata    []byte
}

func (q *Queries) InsertTransition(ctx context.Context, arg InsertTransitionParams) error {
	_, err := q.db.Exec(ctx, insertTransition,
		arg.ExecutionID,
		arg.FromStatus,
		arg.ToStatus,
		arg.TriggeredBy,
		arg.Reason,
		arg.Metadata,
	)
	return err
}

const listTransitionsByExecution = `-- name: ListTransitionsByExecution :many
SELECT transition_id, execution_id, from_status, to_status, triggered_by, reason, metadata, created_at FROM execution_transitions
WHERE execution_id = $1
ORDER BY created_at ASC
`

func (q *Queries) ListTransitionsByExecution(ctx context.Context, executionID uuid.UUID) ([]ExecutionTransition, error) {
	rows, err := q.db.Query(ctx, listTransitionsByExecution, executionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	items := []ExecutionTransition{}
	for rows.Next() {
		var i ExecutionTransition
		if err := rows.Scan(
			&i.TransitionID,
			&i.ExecutionID,
			&i.FromStatus,
			&i.ToStatus,
			&i.TriggeredBy,
			&i.Reason,
			&i.Metadata,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
