apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: nexoraa-temporal-worker-pdb
  namespace: nexoraa-system
  labels:
    app: nexoraa-temporal-worker
    app.kubernetes.io/name: nexoraa-temporal-worker
    app.kubernetes.io/component: temporal-worker
    app.kubernetes.io/part-of: nexoraa-platform
    env: production
spec:
  minAvailable: 2
  selector:
    matchLabels:
      app: nexoraa-temporal-worker
