apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../../base/adot

configMapGenerator:
  - name: adot-tf-values
    envs:
      - adot-config.env
    options:
      disableNameSuffixHash: true

replacements:
  - source:
      kind: ConfigMap
      name: adot-tf-values
      fieldPath: data.AWS_REGION
    targets:
      - select:
          kind: Deployment
          name: adot-amp-collector
        fieldPaths:
          - spec.template.spec.containers.[name=aws-otel-collector].env.[name=AWS_REGION].value
  - source:
      kind: ConfigMap
      name: adot-tf-values
      fieldPath: data.AMP_REMOTE_WRITE_URL
    targets:
      - select:
          kind: Deployment
          name: adot-amp-collector
        fieldPaths:
          - spec.template.spec.containers.[name=aws-otel-collector].env.[name=AWS_PROMETHEUS_ENDPOINT].value
  - source:
      kind: ConfigMap
      name: adot-tf-values
      fieldPath: data.IRSA_ROLE_ARN
    targets:
      - select:
          kind: ServiceAccount
          name: amp-remote-write
        fieldPaths:
          - metadata.annotations.[eks.amazonaws.com/role-arn]
