apiVersion: v1
kind: Namespace
metadata:
  name: nexoraa-system
  labels:
    app.kubernetes.io/part-of: nexoraa-platform
---
apiVersion: v1
kind: Namespace
metadata:
  name: nexoraa-dev
  labels:
    app.kubernetes.io/part-of: nexoraa-platform
